// Audio configuration for the baseball soundboard
export const audioConfig = {
  // Pregame intro settings
  pregameBackgroundVolume: 0.50, // Volume for background music during pregame intro (0.0 to 1.0)
  
  // Player walk-up music (premixed ElevenLabs + music)
  walkups: [
    { id: 1, label: 'Gabriel Zaro', number: '1', file: '/audio/walkups/Walk up 01 Gabriel Zaro.mp3', startTime: 0, fadeIn: true },
    { id: 2, label: 'Henry Ullrich', number: '2', file: '/audio/walkups/Walk up 02 Henry Ullrich.mp3', startTime: 0, fadeIn: true },
    { id: 3, label: 'Sameer Doshi', number: '3', file: '/audio/walkups/Walk up 03 Sameer Doshi.mp3', startTime: 0, fadeIn: true },
    { id: 4, label: 'Oliver Tang', number: '4', file: '/audio/walkups/Walk up 04 Oliver Tang.mp3', startTime: 0, fadeIn: true },
    { id: 5, label: 'Ilyaas Khanshab', number: '5', file: '/audio/walkups/Walk up 05 Ilyaas Khanshab.mp3', startTime: 0, fadeIn: true },
    { id: 6, label: 'Xavier Xia', number: '6', file: '/audio/walkups/Walk up 06 Xavier Xia.mp3', startTime: 0, fadeIn: true },
    { id: 7, label: 'Hunter Smith', number: '7', file: '/audio/walkups/Walk up 07 Hunter Smith.mp3', startTime: 0, fadeIn: true },
    { id: 8, label: 'Jasper Chew', number: '8', file: '/audio/walkups/Walk up 08 Jasper Chew.mp3', startTime: 0, fadeIn: true },
    { id: 9, label: 'Ryan Shin', number: '9', file: '/audio/walkups/Walk up 09 Ryan Shin.mp3', startTime: 0, fadeIn: true },
    { id: 10, label: 'Stan Schmidt', number: '10', file: '/audio/walkups/Walk up 10 Stan Schmidt.mp3', startTime: 0, fadeIn: true },
    { id: 11, label: 'Devin Bedi', number: '11', file: '/audio/walkups/Walk up 11 Devin Bedi.mp3', startTime: 0, fadeIn: true },
    { id: 12, label: 'Nicholas Teseo', number: '12', file: '/audio/walkups/Walk up 12 Nicholas Teseo.mp3', startTime: 0, fadeIn: true },
    { id: 13, label: 'Liam OConnor', number: '13', file: '/audio/walkups/Walk up 13 Liam OConnor.mp3', startTime: 0, fadeIn: true },
  ],

  // Quick situational sound effects
  sounds: [
    { id: 'baby-shark', label: 'Baby Shark', file: '/audio/sounds/Baby Shark.mp3', startTime: 0, fadeIn: false },
    { id: 'calvary', label: 'Calvary Charge', file: '/audio/sounds/Calvary Charge.mp3', startTime: 0, fadeIn: false },
    { id: 'charge', label: 'Charge!', file: '/audio/sounds/Charge Organ.mp3', startTime: 0, fadeIn: false },
    { id: 'riser', label: 'Cinematic Riser', file: '/audio/sounds/Cinematic-riser-boom.mp3', startTime: 0, fadeIn: false },
    { id: 'drums1', label: 'Drums 1', file: '/audio/sounds/drums 1.mp3', startTime: 0, fadeIn: false },
    { id: 'drums2', label: 'Drums 2', file: '/audio/sounds/drums 2.mp3', startTime: 0, fadeIn: false },
    { id: 'drums3', label: 'Drums 3', file: '/audio/sounds/drums 3.mp3', startTime: 0, fadeIn: false },
    { id: 'drums4', label: 'Drums 4', file: '/audio/sounds/drums 4.mp3', startTime: 0, fadeIn: false },
    { id: 'drums5', label: 'Drums 5', file: '/audio/sounds/drums 5.mp3', startTime: 0, fadeIn: false },
    { id: 'drums6', label: 'Drums 6', file: '/audio/sounds/drums 6.mp3', startTime: 0, fadeIn: false },
    { id: 'imperial', label: 'Two Strikes', file: '/audio/sounds/imperial_siren.mp3', startTime: 0, fadeIn: false },
    { id: 'lets-go', label: "Let's Go", file: '/audio/sounds/organ let_s go.mp3', startTime: 0, fadeIn: false },
    { id: 'greek-chant', label: 'Greek Chant', file: '/audio/sounds/organ-greek-chant (1).mp3', startTime: 0, fadeIn: false },
    { id: 'whistle', label: 'Strikeout', file: '/audio/sounds/pc_richard_and_son_whi.mp3', startTime: 0, fadeIn: false },
    { id: 'james-bond', label: 'Walk (007)', file: '/audio/sounds/007 James Bond Theme.mp3', startTime: 36, fadeIn: true },
    { id: 'walkin', label: "Walk (I'm Walkin')", file: '/audio/sounds/Fats Domino - I_m Walkin_.mp3', startTime: 0, fadeIn: false },
    { id: 'jaws', label: 'Walk (Jaws Theme)', file: '/audio/sounds/Jaws - Theme.mp3', startTime: 55, fadeIn: true },
    { id: 'song33', label: 'Walk (Smooth Criminal)', file: '/audio/songs/Smooth Criminal.mp3', startTime: 13, fadeIn: true },
    { id: 'take-walk', label: 'Walk (Take a Walk)', file: '/audio/sounds/Take a Walk.mp3', startTime: 90, fadeIn: true },
    { id: 'boots-walking', label: 'Walk (These Boots)', file: '/audio/sounds/These Boots Are Made For Walking.mp3', startTime: 0, fadeIn: false },
    { id: 'walk-man', label: 'Walk (Walk Like a Man)', file: '/audio/sounds/Walk Like a Man.mp3', startTime: 43, fadeIn: true },
    { id: 'song41', label: 'Walk (Walk This Way)', file: '/audio/songs/Walk This Way.mp3', startTime: 60, fadeIn: true },
    { id: 'all-star', label: 'Run/Hit: All Star', file: '/audio/sounds/All Star.mp3', startTime: 52, fadeIn: true },
    { id: 'cant-touch', label: "Run/Hit: U Can't Touch This", file: "/audio/sounds/U Can_t Touch This.mp3", startTime: 0, fadeIn: false },
    { id: 'celebration', label: 'Run/Hit: Celebration', file: '/audio/sounds/Celebration.mp3', startTime: 32, fadeIn: true },
    { id: 'dogs-out', label: 'Run/Hit: Who Let the Dogs Out', file: '/audio/sounds/Who Let The Dogs Out.mp3', startTime: 0, fadeIn: false },
    { id: 'ff-victory', label: 'Run/Hit: Final Fantasy Victory', file: '/audio/sounds/final-fantasy-vii-victory-fanfare.mp3', startTime: 0, fadeIn: false },
    { id: 'i-feel-good', label: 'Run/Hit: I Got You (I Feel Good)', file: '/audio/sounds/I Got You (I Feel Good).mp3', startTime: 0, fadeIn: false },
    { id: 'level-up', label: 'Run/Hit: Level Up', file: '/audio/sounds/Level Up.mp3', startTime: 6, fadeIn: true },
    { id: 'mario-star', label: 'Run/Hit: Mario Star Theme', file: '/audio/sounds/mario_star_theme.mp3', startTime: 0, fadeIn: false },
    { id: 'mario-victory', label: 'Run/Hit: Super Mario Victory', file: '/audio/sounds/super_mario_victory.mp3', startTime: 0, fadeIn: false },
    { id: 'whoomp', label: 'Run/Hit: Whoomp! (There It Is)', file: '/audio/sounds/Whoomp! (There It Is).mp3', startTime: 30, fadeIn: true },
  ],

  // Full-length songs for between innings
  songs: [
    { id: 'song1', label: '24K Magic', file: '/audio/songs/24K Magic.mp3', startTime: 22, fadeIn: true },
    //{ id: 'song2', label: 'All I Do Is Win', file: '/audio/songs/All I Do Is Win.mp3', startTime: 0, fadeIn: true },
    { id: 'song2b', label: 'All Star', file: '/audio/songs/All Star.mp3', startTime: 15, fadeIn: true },
    { id: 'song3', label: 'Are You Gonna Go My Way', file: '/audio/songs/Are You Gonna Go My Way.mp3', startTime: 0, fadeIn: true },
    { id: 'song4', label: "Baba O'Riley", file: '/audio/songs/Baba O_Riley.mp3', startTime: 32, fadeIn: true },
    { id: 'song5', label: 'Back In Black', file: '/audio/songs/Back In Black.mp3', startTime: 5, fadeIn: true },
    { id: 'song5b', label: 'Bad To The Bone', file: '/audio/songs/Bad To The Bone.mp3', startTime: 5, fadeIn: true },
    //{ id: 'song6', label: 'Believer', file: '/audio/songs/Believer.mp3', startTime: 0, fadeIn: true },
    { id: 'song7', label: 'Blitzkrieg Bop', file: '/audio/songs/Blitzkrieg Bop.mp3', startTime: 0, fadeIn: true },
    { id: 'song7b', label: "Can't Hold Us", file: '/audio/songs/Can_t Hold Us.mp3', startTime: 0, fadeIn: true },
    { id: 'song8', label: "Can't Stop The Feeling!", file: '/audio/songs/Can_t Stop The Feeling!.mp3', startTime: 41, fadeIn: true },
    { id: 'song9', label: 'Centerfield', file: '/audio/songs/Centerfield.mp3', startTime: 0, fadeIn: true },
    { id: 'song10', label: 'Crazy Little Thing Called Love', file: '/audio/songs/Crazy Little Thing Called Love.mp3', startTime: 0, fadeIn: true },
    { id: 'song11', label: 'Crazy Train', file: '/audio/songs/Crazy Train.mp3', startTime: 0, fadeIn: true },
    { id: 'song12', label: "Don't Stop 'til You Get Enough", file: '/audio/songs/Don_t Stop _til You Get Enough.mp3', startTime: 14, fadeIn: true },
    { id: 'song13', label: 'Empire State of Mind', file: '/audio/songs/Empire State Of Mind.mp3', startTime: 54, fadeIn: true },
    //{ id: 'song14', label: 'Enter Sandman', file: '/audio/songs/Enter Sandman.mp3', startTime: 0, fadeIn: true },
    { id: 'song14b', label: 'Espresso', file: '/audio/songs/Espresso.mp3', startTime: 0, fadeIn: true },
    { id: 'song15', label: 'Eye of the Tiger', file: '/audio/songs/Eye of the Tiger.mp3', startTime: 0, fadeIn: true },
    //{ id: 'song16', label: 'Trap Queen', file: '/audio/songs/Fetty Wap - Trap Queen (Clean).mp3', startTime: 0, fadeIn: true },
    { id: 'song16b', label: 'Happy', file: '/audio/songs/Happy.mp3', startTime: 0, fadeIn: true },
    { id: 'song17', label: 'Hells Bells', file: '/audio/songs/Hells Bells.mp3', startTime: 19, fadeIn: true },
    { id: 'song18', label: 'Highway to Hell', file: '/audio/songs/Highway to Hell.mp3', startTime: 0, fadeIn: true },
    { id: 'song19', label: 'I Believe That We Will Win', file: '/audio/songs/I Believe That We Will Win (World Anthem).mp3', startTime: 0, fadeIn: true },
    { id: 'song20', label: "Steve's Lava Chicken", file: '/audio/songs/Jack Black - Steve_s Lava Chicken.mp3', startTime: 8, fadeIn: true },
    //{ id: 'song20b', label: "Steve's Lava Chicken (Extended)", file: '/audio/songs/Jack Black - Steve_s Lava Chicken (Extended Version).mp3', startTime: 0, fadeIn: true },
    { id: 'song21', label: 'Jump Around', file: '/audio/songs/Jump Around.mp3', startTime: 0, fadeIn: true },
    { id: 'song22', label: 'Kickstart My Heart', file: '/audio/songs/Kickstart My Heart.mp3', startTime: 0, fadeIn: true },
    { id: 'song23', label: "Livin' on a Prayer", file: "/audio/songs/Livin on a Prayer.mp3", startTime: 15, fadeIn: true },
    { id: 'song24', label: 'Lose Yourself', file: '/audio/songs/Lose Yourself.mp3', startTime: 30, fadeIn: true },
    { id: 'song25', label: 'New York Groove', file: '/audio/songs/New York Groove.mp3', startTime: 46, fadeIn: true },
    { id: 'song25b', label: "No Longer Bound (I'm Free)", file: "/audio/songs/No Longer Bound (I_m Free).mp3", startTime: 17, fadeIn: true },
    { id: 'song26', label: "No Sleep 'Til Brooklyn", file: '/audio/songs/No Sleep _Til Brooklyn.mp3', startTime: 0, fadeIn: true },
    { id: 'song27', label: 'Paradise City', file: '/audio/songs/Paradise City.mp3', startTime: 0, fadeIn: true },
    { id: 'song28', label: 'Never Gonna Give You Up', file: '/audio/songs/Rick Astley - Never Gonna Give You Up.mp3', startTime: 0, fadeIn: true },
    { id: 'song28b', label: 'Renegade', file: '/audio/songs/Renegade.mp3', startTime: 42, fadeIn: true },
    { id: 'song29', label: 'Sabotage', file: '/audio/songs/Sabotage.mp3', startTime: 0, fadeIn: true },
    { id: 'song30', label: 'Seven Nation Army', file: '/audio/songs/Seven Nation Army.mp3', startTime: 0, fadeIn: true },
    { id: 'song31', label: 'Shook Ones, Pt. II', file: '/audio/songs/Shook Ones, Pt. II.mp3', startTime: 23, fadeIn: true },
    { id: 'song31b', label: 'Shake It Off', file: '/audio/songs/Shake It Off.mp3', startTime: 0, fadeIn: true },
    { id: 'song32', label: 'Shoot To Thrill', file: '/audio/songs/Shoot To Thrill.mp3', startTime: 0, fadeIn: true },
    { id: 'song32b', label: 'Shooting Stars', file: '/audio/songs/Shooting Stars.mp3', startTime: 18, fadeIn: true },
    { id: 'song33', label: 'Smooth Criminal', file: '/audio/songs/Smooth Criminal.mp3', startTime: 13, fadeIn: true },
    { id: 'song33b', label: 'Summer Love', file: '/audio/songs/Summer Love.mp3', startTime: 0, fadeIn: true },
    { id: 'song33c', label: 'Swag Surfin', file: '/audio/songs/Swag Surfin.mp3', startTime: 0, fadeIn: true },
    { id: 'song34', label: 'Sweet Caroline', file: '/audio/songs/Sweet Caroline.mp3', startTime: 0, fadeIn: true },
    { id: 'song35', label: "Sweet Child O' Mine", file: '/audio/songs/Sweet Child O_ Mine.mp3', startTime: 0, fadeIn: true },
    { id: 'song35b', label: 'Sweet Home Alabama', file: '/audio/songs/Sweet Home Alabama.mp3', startTime: 15, fadeIn: true },
    { id: 'song36', label: 'Take Me Out To The Ball Game', file: '/audio/songs/Take Me Out To The Ball Game.mp3', startTime: 0, fadeIn: true },
    { id: 'song36b', label: 'The Final Countdown', file: '/audio/songs/The Final Countdown.mp3', startTime: 12, fadeIn: true },
    { id: 'song37', label: 'The Imperial March', file: '/audio/songs/The Imperial March.mp3', startTime: 0, fadeIn: true },
    { id: 'song38', label: 'Theme From New York, New York', file: '/audio/songs/Theme From New York, New York.mp3', startTime: 0, fadeIn: true },
    { id: 'song38b', label: 'Thunder', file: '/audio/songs/Thunder.mp3', startTime: 0, fadeIn: true },
    { id: 'song39', label: 'Thunderstruck', file: '/audio/songs/Thunderstruck.mp3', startTime: 0, fadeIn: true },
    { id: 'song40', label: 'Uptown Funk', file: '/audio/songs/Uptown Funk.mp3', startTime: 13, fadeIn: true },
    { id: 'song42', label: 'We Ready', file: '/audio/songs/We Ready.mp3', startTime: 0, fadeIn: true },
    { id: 'song43', label: 'We Will Rock You', file: '/audio/songs/We Will Rock You.mp3', startTime: 0, fadeIn: true },
    { id: 'song44', label: 'Welcome To The Jungle', file: '/audio/songs/Welcome To The Jungle.mp3', startTime: 0, fadeIn: true },
    { id: 'song44b', label: 'Whole Lotta Love', file: '/audio/songs/Whole Lotta Love.mp3', startTime: 0, fadeIn: true },
    { id: 'song45', label: 'YMCA', file: '/audio/songs/YMCA.mp3', startTime: 0, fadeIn: true },
    { id: 'song46', label: 'You Shook Me All Night Long', file: '/audio/songs/You Shook Me All Night Long.mp3', startTime: 0, fadeIn: true },
  ],

  // Selectable background music for pregame intro sequence
  pregameBackgroundOptions: [
    { id: 'song4', label: "Baba O'Riley", file: '/audio/songs/Baba O_Riley.mp3', startTime: 30, fadeIn: true },
    { id: 'song15', label: 'Eye of the Tiger', file: '/audio/songs/Eye of the Tiger.mp3', startTime: 0, fadeIn: true },
    { id: 'song5', label: 'Back In Black', file: '/audio/songs/Back In Black.mp3', startTime: 5, fadeIn: true },
    { id: 'song37', label: 'The Imperial March', file: '/audio/songs/The Imperial March.mp3', startTime: 0, fadeIn: true },
    { id: 'song44', label: 'Welcome To The Jungle', file: '/audio/songs/Welcome To The Jungle.mp3', startTime: 0, fadeIn: true },
    { id: 'song39', label: 'Thunderstruck', file: '/audio/songs/Thunderstruck.mp3', startTime: 0, fadeIn: true },
    { id: 'song21', label: 'Jump Around', file: '/audio/songs/Jump Around.mp3', startTime: 0, fadeIn: true },
  ],

  // Background loops for pregame announcements (player intros)
  pregame: [
    { id: 'intro-zaro', label: 'Gabriel Zaro Intro', file: '/audio/pregame/Intro 01 Gabriel Zaro.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-ullrich', label: 'Henry Ullrich Intro', file: '/audio/pregame/Intro 02 Henry Ullrich.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-doshi', label: 'Sameer Doshi Intro', file: '/audio/pregame/Intro 03 Sameer Doshi.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-tang', label: 'Oliver Tang Intro', file: '/audio/pregame/Intro 04 Oliver Tang.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-khanshab', label: 'Ilyaas Khanshab Intro', file: '/audio/pregame/Intro 05 Ilyaas Khanshab.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-xia', label: 'Xavier Xia Intro', file: '/audio/pregame/Intro 06 Xavier Xia.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-smith', label: 'Hunter Smith Intro', file: '/audio/pregame/Intro 07 Hunter Smith.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-chew', label: 'Jasper Chew Intro', file: '/audio/pregame/Intro 08 Jasper Chew.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-shin', label: 'Ryan Shin Intro', file: '/audio/pregame/Intro 09 Ryan Shin.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-schmidt', label: 'Stan Schmidt Intro', file: '/audio/pregame/Intro 10 Stan Schmidt.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-bedi', label: 'Devon Bedi Intro', file: '/audio/pregame/Intro 11 Devon Bedi.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-teseo', label: 'Nicholas Teseo Intro', file: '/audio/pregame/Intro 12 Nicholas Teseo.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-oconnor', label: 'Liam OConnor Intro', file: '/audio/pregame/Intro 13 Liam OConnor.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-end', label: 'Intro End', file: '/audio/pregame/Intro end.mp3', startTime: 0, fadeIn: false },
    { id: 'intro-monsters', label: 'Lake Monsters Intro', file: '/audio/pregame/Intro Lake Monsters lineup.mp3', startTime: 0, fadeIn: false },
  ],
};


