// Audio configuration for the baseball soundboard
// Cache busting version - automatically set to git commit hash at build time
const AUDIO_VERSION = typeof __APP_VERSION__ !== 'undefined' ? __APP_VERSION__ : Date.now().toString();

// Helper function to add cache-busting parameter
const audioUrl = (path) => `${path}?v=${AUDIO_VERSION}`;

export const audioConfig = {
  // Pregame intro settings
  pregameBackgroundVolume: 0.50, // Volume for background music during pregame intro (0.0 to 1.0)
  
  // Player walk-up music (premixed ElevenLabs + music)
  walkups: [
    { id: 1, label: 'Gabriel Zaro', number: '1', file: audioUrl('/audio/walkups/walk-up-01-gabriel-zaro.mp3'), startTime: 0, fadeIn: true },
    { id: 2, label: 'Henry Ullrich', number: '2', file: audioUrl('/audio/walkups/walk-up-02-henry-ullrich.mp3'), startTime: 0, fadeIn: true },
    { id: 3, label: 'Sameer Doshi', number: '3', file: audioUrl('/audio/walkups/walk-up-03-sameer-doshi.mp3'), startTime: 0, fadeIn: true },
    { id: 4, label: 'Oliver Tang', number: '4', file: audioUrl('/audio/walkups/walk-up-04-oliver-tang.mp3'), startTime: 0, fadeIn: true },
    { id: 5, label: 'Ilyaas Khanshab', number: '5', file: audioUrl('/audio/walkups/walk-up-05-ilyaas-khanshab.mp3'), startTime: 0, fadeIn: true },
    { id: 6, label: 'Xavier Xia', number: '6', file: audioUrl('/audio/walkups/walk-up-06-xavier-xia.mp3'), startTime: 0, fadeIn: true },
    { id: 7, label: 'Hunter Smith', number: '7', file: audioUrl('/audio/walkups/walk-up-07-hunter-smith.mp3'), startTime: 0, fadeIn: true },
    { id: 8, label: 'Jasper Chew', number: '8', file: audioUrl('/audio/walkups/walk-up-08-jasper-chew.mp3'), startTime: 0, fadeIn: true },
    { id: 9, label: 'Ryan Shin', number: '9', file: audioUrl('/audio/walkups/walk-up-09-ryan-shin.mp3'), startTime: 0, fadeIn: true },
    { id: 10, label: 'Stan Schmidt', number: '10', file: audioUrl('/audio/walkups/walk-up-10-stan-schmidt.mp3'), startTime: 0, fadeIn: true },
    { id: 11, label: 'Devin Bedi', number: '11', file: audioUrl('/audio/walkups/walk-up-11-devin-bedi.mp3'), startTime: 0, fadeIn: true },
    { id: 12, label: 'Nicholas Teseo', number: '12', file: audioUrl('/audio/walkups/walk-up-12-nicholas-teseo.mp3'), startTime: 0, fadeIn: true },
    { id: 13, label: 'Liam OConnor', number: '13', file: audioUrl('/audio/walkups/walk-up-13-liam-oconnor.mp3'), startTime: 0, fadeIn: true },
  ],

  // Quick situational sound effects
  sounds: [
    // At Bat - Short clips for during at-bats
    { id: 'addams-family', label: 'Addams Family', file: audioUrl('/audio/sounds/addams-family-theme.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'imperial', label: 'Two Strikes', file: audioUrl('/audio/sounds/imperial-siren.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'mario-coin-atbat', label: 'Mario Coin', file: audioUrl('/audio/sounds/mario-coin.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'slide-whistle', label: 'Slide Whistle 1', file: audioUrl('/audio/sounds/slide-whistle.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'slide-whistle2', label: 'Slide Whistle 2', file: audioUrl('/audio/sounds/slide-whistle2.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'sonic-ring-atbat', label: 'Sonic Ring', file: audioUrl('/audio/sounds/sonic-ring.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'strikeout-mario', label: 'Strikeout: Mario', file: audioUrl('/audio/sounds/super-mario-death.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'strikeout-megaman', label: 'Strikeout: Mega Man', file: audioUrl('/audio/sounds/megamandeath.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'strikeout-pacman', label: 'Strikeout: Pac-Man', file: audioUrl('/audio/sounds/pac-man-death.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'strikeout-pc-richards', label: 'Strikeout: PC Richards', file: audioUrl('/audio/sounds/pc-richard-and-son-whi.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    { id: 'whistle-atbat', label: 'Whistle', file: audioUrl('/audio/sounds/whistle.mp3'), startTime: 0, fadeIn: false, category: 'at-bat', initialDelay: 0.75 },
    
    // Hype - Crowd hype and energy sounds
    { id: 'baby-shark', label: 'Baby Shark', file: audioUrl('/audio/sounds/baby-shark.mp3'), startTime: 16, fadeIn: true, category: 'hype' },
    { id: 'calvary', label: 'Calvary Charge', file: audioUrl('/audio/sounds/calvary-charge.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'centerfield-claps', label: 'Centerfield Claps', file: audioUrl('/audio/sounds/centerfield-claps.mp3'), startTime: 0, fadeIn: false, category: 'hype', initialDelay: 0.75 },
    { id: 'charge', label: 'Charge!', file: audioUrl('/audio/sounds/charge-organ.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'drums1', label: 'Drums 1', file: audioUrl('/audio/sounds/drums-1.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'drums2', label: 'Drums 2', file: audioUrl('/audio/sounds/drums-2.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'drums3', label: 'Drums 3', file: audioUrl('/audio/sounds/drums-3.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'drums4', label: 'Drums 4', file: audioUrl('/audio/sounds/drums-4.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'drums5', label: 'Drums 5', file: audioUrl('/audio/sounds/drums-5.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'drums6', label: 'Drums 6', file: audioUrl('/audio/sounds/drums-6.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'greek-chant', label: 'Greek Chant', file: audioUrl('/audio/sounds/organ-greek-chant-1.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'hey-baby', label: 'Hey Baby', file: audioUrl('/audio/sounds/hey-baby.mp3'), startTime: 18, fadeIn: true, category: 'hype' },
    { id: 'hey-song', label: 'Hey Song', file: audioUrl('/audio/sounds/hey-song.mp3'), startTime: 22, fadeIn: true, category: 'hype' },
    { id: 'lets-go', label: "Let's Go", file: audioUrl('/audio/sounds/organ-let-s-go.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'make-hands-clap', label: 'Make Your Hands Clap', file: audioUrl('/audio/sounds/make-your-hands-clap.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    { id: 'lava-chicken', label: "Steve's Lava Chicken", file: audioUrl('/audio/songs/lava-chicken.mp3'), startTime: 8, fadeIn: true, category: 'hype' },
    { id: 'we-will-rock-you-hype', label: 'We Will Rock You', file: audioUrl('/audio/songs/we-will-rock-you.mp3'), startTime: 0, fadeIn: false, category: 'hype' },
    
    // Steal - For stolen bases
    { id: 'bad-to-bone', label: 'Bad To The Bone', file: audioUrl('/audio/songs/bad-to-the-bone.mp3'), startTime: 10, fadeIn: false, category: 'steal' },
    { id: 'cash-register', label: 'Cash Register', file: audioUrl('/audio/sounds/cash-register.mp3'), startTime: 0, fadeIn: false, category: 'steal', initialDelay: 0.75 },
    { id: 'metal-gear-alert', label: 'Metal Gear Alert', file: audioUrl('/audio/sounds/metal-gear-alert.mp3'), startTime: 0, fadeIn: false, category: 'steal', initialDelay: 0.75 },
    { id: 'mission-impossible', label: 'Mission Impossible', file: audioUrl('/audio/sounds/mission-impossible.mp3'), startTime: 0, fadeIn: false, category: 'steal' },
    { id: 'pink-panther', label: 'Pink Panther', file: audioUrl('/audio/sounds/pink-panther.mp3'), startTime: 0, fadeIn: false, category: 'steal' },
    { id: 'race-track', label: 'Race Track', file: audioUrl('/audio/sounds/race-track.mp3'), startTime: 0, fadeIn: false, category: 'steal' },
    { id: 'road-runner', label: 'Road Runner', file: audioUrl('/audio/sounds/road-runner.mp3'), startTime: 0, fadeIn: false, category: 'steal' },
    { id: 'song33', label: 'Smooth Criminal', file: audioUrl('/audio/songs/smooth-criminal.mp3'), startTime: 91, fadeIn: true, category: 'steal' },
    { id: 'zip-scramble', label: 'Zip Scramble', file: audioUrl('/audio/sounds/zipscramble.mp3'), startTime: 0, fadeIn: false, category: 'steal' },
    
    // Walk - For when batter walks
    { id: 'james-bond', label: '007', file: audioUrl('/audio/sounds/007-james-bond-theme.mp3'), startTime: 36, fadeIn: true, category: 'walk' },
    { id: 'walkin', label: "I'm Walkin'", file: audioUrl('/audio/sounds/i-m-walkin.mp3'), startTime: 0, fadeIn: false, category: 'walk' },
    { id: 'jaws', label: 'Jaws Theme', file: audioUrl('/audio/sounds/jaws-theme.mp3'), startTime: 55, fadeIn: true, category: 'walk' },
    { id: 'take-walk', label: 'Take a Walk', file: audioUrl('/audio/sounds/take-a-walk.mp3'), startTime: 90, fadeIn: true, category: 'walk' },
    { id: 'boots-walking', label: 'These Boots', file: audioUrl('/audio/sounds/these-boots-are-made-for-walking.mp3'), startTime: 0, fadeIn: false, category: 'walk' },
    { id: 'walk-man', label: 'Walk Like a Man', file: audioUrl('/audio/sounds/walk-like-a-man.mp3'), startTime: 43, fadeIn: true, category: 'walk' },
    { id: 'song41', label: 'Walk This Way', file: audioUrl('/audio/songs/walk-this-way.mp3'), startTime: 60, fadeIn: true, category: 'walk' },
    
    // Victory Short - Quick celebration clips
    { id: 'boomshakalaka', label: 'Boomshakalaka', file: audioUrl('/audio/sounds/boomshakalaka.mp3'), startTime: 0, fadeIn: false, category: 'hit-short', initialDelay: 0.75 },
    { id: 'cowabunga', label: 'Cowabunga', file: audioUrl('/audio/sounds/tmnt-cowabunga.mp3'), startTime: 0, fadeIn: false, category: 'hit-short', initialDelay: 0.75 },
    { id: 'dj-air-horn', label: 'DJ Air Horn', file: audioUrl('/audio/sounds/dj-air-horn.mp3'), startTime: 0, fadeIn: false, category: 'hit-short', initialDelay: 0.75 },
    { id: 'ff-victory', label: 'Final Fantasy Victory', file: audioUrl('/audio/sounds/final-fantasy-vii-victory-fanfare.mp3'), startTime: 0, fadeIn: false, category: 'hit-short' },
    { id: 'hadouken', label: 'Hadouken', file: audioUrl('/audio/sounds/hadouken.mp3'), startTime: 0, fadeIn: false, category: 'hit-short', initialDelay: 0.75 },
    { id: 'mario-star', label: 'Mario Star Theme', file: audioUrl('/audio/sounds/mario-star-theme.mp3'), startTime: 0, fadeIn: false, category: 'hit-short' },
    { id: 'mario-victory', label: 'Super Mario Victory', file: audioUrl('/audio/sounds/super-mario-victory.mp3'), startTime: 0, fadeIn: false, category: 'hit-short' },
    { id: 'mega-man-x', label: 'Mega Man X', file: audioUrl('/audio/sounds/mega-man-x-victory.mp3'), startTime: 0, fadeIn: false, category: 'hit-short' },
    { id: 'price-is-right', label: 'Price is Right', file: audioUrl('/audio/sounds/the-price-is-right.mp3'), startTime: 0, fadeIn: false, category: 'hit-short' },
    { id: 'sonic-rings', label: 'Sonic Rings', file: audioUrl('/audio/sounds/sonic-rings-3x.mp3'), startTime: 0, fadeIn: false, category: 'hit-short', initialDelay: 0.75 },
    { id: 'zelda-item', label: 'Zelda 1', file: audioUrl('/audio/sounds/zelda-item.mp3'), startTime: 0, fadeIn: false, category: 'hit-short' },
    { id: 'zelda-item2', label: 'Zelda 2', file: audioUrl('/audio/sounds/zelda-item2.mp3'), startTime: 0, fadeIn: false, category: 'hit-short' },
    
    // Victory Long - Longer celebration clips
    { id: 'all-star', label: 'All Star', file: audioUrl('/audio/sounds/all-star.mp3'), startTime: 52, fadeIn: true, category: 'hit-long' },
    { id: 'cant-touch', label: "U Can't Touch This", file: audioUrl("/audio/sounds/u-can-t-touch-this.mp3"), startTime: 0, fadeIn: false, category: 'hit-long' },
    { id: 'celebration', label: 'Celebration', file: audioUrl('/audio/sounds/celebration.mp3'), startTime: 32, fadeIn: true, category: 'hit-long' },
    { id: 'dogs-out', label: 'Who Let the Dogs Out', file: audioUrl('/audio/sounds/who-let-the-dogs-out.mp3'), startTime: 0, fadeIn: false, category: 'hit-long' },
    { id: 'i-feel-good', label: 'I Got You (I Feel Good)', file: audioUrl('/audio/sounds/i-got-you-i-feel-good.mp3'), startTime: 0, fadeIn: false, category: 'hit-long' },
    { id: 'level-up', label: 'Level Up', file: audioUrl('/audio/sounds/level-up.mp3'), startTime: 6, fadeIn: true, category: 'hit-long' },
    { id: 'seinfeld', label: 'Seinfeld', file: audioUrl('/audio/sounds/seinfeld-opening.mp3'), startTime: 0, fadeIn: false, category: 'hit-long' },
    { id: 'whoomp', label: 'Whoomp! (There It Is)', file: audioUrl('/audio/sounds/whoomp-there-it-is.mp3'), startTime: 30, fadeIn: true, category: 'hit-long' },
  ],

  // Full-length songs for between innings
  songs: [
    { id: 'song1', label: '24K Magic', file: audioUrl('/audio/songs/24k-magic.mp3'), startTime: 22, fadeIn: true, category: 'upbeat' },
    { id: 'song2b', label: 'All Star', file: audioUrl('/audio/songs/all-star.mp3'), startTime: 15, fadeIn: true, category: 'rock' },
    { id: 'song3', label: 'Are You Gonna Go My Way', file: audioUrl('/audio/songs/are-you-gonna-go-my-way.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    //{ id: 'song4', label: "Baba O'Riley", file: audioUrl('/audio/songs/baba-o-riley.mp3'), startTime: 32, fadeIn: true, category: 'rock' },
    { id: 'song5', label: 'Back In Black', file: audioUrl('/audio/songs/back-in-black.mp3'), startTime: 5, fadeIn: true, category: 'rock' },
    { id: 'song5b', label: 'Bad To The Bone', file: audioUrl('/audio/songs/bad-to-the-bone.mp3'), startTime: 10, fadeIn: true, category: 'rock' },
    { id: 'song7', label: 'Blitzkrieg Bop', file: audioUrl('/audio/songs/blitzkrieg-bop.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song7b', label: "Can't Hold Us", file: audioUrl('/audio/songs/can-t-hold-us.mp3'), startTime: 0, fadeIn: false, category: 'hip-hop' },
    { id: 'song8', label: "Can't Stop The Feeling!", file: audioUrl('/audio/songs/can-t-stop-the-feeling.mp3'), startTime: 41, fadeIn: true, category: 'upbeat' },
    { id: 'song9', label: 'Centerfield', file: audioUrl('/audio/songs/centerfield.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song9b', label: 'Come and Get Your Love', file: audioUrl('/audio/songs/come-and-get-your-love.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song10', label: 'Crazy Little Thing Called Love', file: audioUrl('/audio/songs/crazy-little-thing-called-love.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song11', label: 'Crazy Train', file: audioUrl('/audio/songs/crazy-train.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song12', label: "Don't Stop 'til You Get Enough", file: audioUrl('/audio/songs/don-t-stop-til-you-get-enough.mp3'), startTime: 14, fadeIn: true, category: 'upbeat' },
    { id: 'song13', label: 'Empire State of Mind', file: audioUrl('/audio/songs/empire-state-of-mind.mp3'), startTime: 54, fadeIn: true, category: 'hip-hop' },
    { id: 'song14', label: 'Enter Sandman', file: audioUrl('/audio/songs/enter-sandman.mp3'), startTime: 0, fadeIn: true, category: 'villain' },
    { id: 'song14b', label: 'Espresso', file: audioUrl('/audio/songs/espresso.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song15', label: 'Eye of the Tiger', file: audioUrl('/audio/songs/eye-of-the-tiger.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song16a', label: "Gettin Jiggy Wit It", file: audioUrl("/audio/songs/gettin-jiggy-wit-it.mp3"), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song16a2', label: 'Get The Party Started', file: audioUrl('/audio/songs/get-the-party-started.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song16b', label: 'Happy', file: audioUrl('/audio/songs/happy.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song16c', label: 'Hooked on a Feeling', file: audioUrl('/audio/songs/hooked-on-a-feeling.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song17', label: 'Hells Bells', file: audioUrl('/audio/songs/hells-bells.mp3'), startTime: 19, fadeIn: true, category: 'rock' },
    { id: 'song18', label: 'Highway to Hell', file: audioUrl('/audio/songs/highway-to-hell.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song18b', label: 'Hypnotize', file: audioUrl('/audio/songs/hypnotize.mp3'), startTime: 0, fadeIn: false, category: 'hip-hop' },
    { id: 'song19', label: 'I Believe That We Will Win', file: audioUrl('/audio/songs/i-believe-that-we-will-win-world-anthem.mp3'), startTime: 0, fadeIn: false, category: 'hip-hop' },
    { id: 'song21', label: 'Jump Around', file: audioUrl('/audio/songs/jump-around.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song22', label: 'Kickstart My Heart', file: audioUrl('/audio/songs/kickstart-my-heart.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song23', label: "Livin' on a Prayer", file: audioUrl("/audio/songs/livin-on-a-prayer.mp3"), startTime: 15, fadeIn: true, category: 'rock' },
    { id: 'song24', label: 'Lose Yourself', file: audioUrl('/audio/songs/lose-yourself.mp3'), startTime: 30, fadeIn: true, category: 'hip-hop' },
    { id: 'song24b', label: 'Mr. Brightside', file: audioUrl('/audio/songs/mr-brightside.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song25', label: 'New York Groove', file: audioUrl('/audio/songs/new-york-groove.mp3'), startTime: 46, fadeIn: true, category: 'rock' },
    { id: 'song25b', label: "No Longer Bound (I'm Free)", file: audioUrl("/audio/songs/no-longer-bound-i-m-free.mp3"), startTime: 17, fadeIn: true, category: 'upbeat' },
    { id: 'song26', label: "No Sleep 'Til Brooklyn", file: audioUrl('/audio/songs/no-sleep-til-brooklyn.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song27', label: 'Paradise City', file: audioUrl('/audio/songs/paradise-city.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song27a', label: 'Raise Your Glass', file: audioUrl('/audio/songs/raise-your-glass.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song28', label: 'Never Gonna Give You Up', file: audioUrl('/audio/songs/never-gonna-give-you-up.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song28b', label: 'Renegade', file: audioUrl('/audio/songs/renegade.mp3'), startTime: 42, fadeIn: true, category: 'rock' },
    { id: 'song29', label: 'Sabotage', file: audioUrl('/audio/songs/sabotage.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song29b', label: 'September', file: audioUrl('/audio/songs/september.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song30', label: 'Seven Nation Army', file: audioUrl('/audio/songs/seven-nation-army.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song31', label: 'Shook Ones, Pt. II', file: audioUrl('/audio/songs/shook-ones-pt.-ii.mp3'), startTime: 23, fadeIn: true, category: 'hip-hop' },
    { id: 'song31b', label: 'Shake It Off', file: audioUrl('/audio/songs/shake-it-off.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song32', label: 'Shoot To Thrill', file: audioUrl('/audio/songs/shoot-to-thrill.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song32b', label: 'Shooting Stars', file: audioUrl('/audio/songs/shooting-stars.mp3'), startTime: 18, fadeIn: true, category: 'upbeat' },
    { id: 'song33', label: 'Smooth Criminal', file: audioUrl('/audio/songs/smooth-criminal.mp3'), startTime: 13, fadeIn: true, category: 'upbeat' },
    { id: 'song33_1', label: 'So What', file: audioUrl('/audio/songs/so-what.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song33a', label: 'Start Me Up', file: audioUrl('/audio/songs/start-me-up.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song33b', label: 'Summer Love', file: audioUrl('/audio/songs/summer-love.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song33b2', label: 'Summertime', file: audioUrl('/audio/songs/summertime.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song33b3', label: 'Surrender', file: audioUrl('/audio/songs/surrender.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song33c', label: 'Swag Surfin', file: audioUrl('/audio/songs/swag-surfin.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song33d', label: 'Stayin Alive', file: audioUrl('/audio/songs/stayin-alive.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song34', label: 'Sweet Caroline', file: audioUrl('/audio/songs/sweet-caroline.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song35', label: "Sweet Child O' Mine", file: audioUrl('/audio/songs/sweet-child-o-mine.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song35b', label: 'Sweet Home Alabama', file: audioUrl('/audio/songs/sweet-home-alabama.mp3'), startTime: 15, fadeIn: true, category: 'rock' },
    { id: 'song36a', label: 'Take on Me', file: audioUrl('/audio/songs/take-on-me.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song36b', label: 'The Final Countdown', file: audioUrl('/audio/songs/the-final-countdown.mp3'), startTime: 12, fadeIn: true, category: 'upbeat' },
    { id: 'song37', label: 'The Imperial March', file: audioUrl('/audio/songs/the-imperial-march.mp3'), startTime: 0, fadeIn: false, category: 'villain' },
    { id: 'song38', label: 'Theme From New York, New York', file: audioUrl('/audio/songs/theme-from-new-york-new-york.mp3'), startTime: 0, fadeIn: false, category: 'game-end' },
    { id: 'song38b', label: 'Thunder', file: audioUrl('/audio/songs/thunder.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song39', label: 'Thunderstruck', file: audioUrl('/audio/songs/thunderstruck.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song40', label: 'Uptown Funk', file: audioUrl('/audio/songs/uptown-funk.mp3'), startTime: 13, fadeIn: true, category: 'upbeat' },
    { id: 'song42', label: 'We Ready', file: audioUrl('/audio/songs/we-ready.mp3'), startTime: 0, fadeIn: false, category: 'hip-hop' },
    { id: 'song43', label: 'We Will Rock You', file: audioUrl('/audio/songs/we-will-rock-you.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song44', label: 'Welcome To The Jungle', file: audioUrl('/audio/songs/welcome-to-the-jungle.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song44b', label: 'Whole Lotta Love', file: audioUrl('/audio/songs/whole-lotta-love.mp3'), startTime: 0, fadeIn: false, category: 'rock' },
    { id: 'song45', label: 'YMCA', file: audioUrl('/audio/songs/ymca.mp3'), startTime: 0, fadeIn: false, category: 'upbeat' },
    { id: 'song46', label: 'You Shook Me All Night Long', file: audioUrl('/audio/songs/you-shook-me-all-night-long.mp3'), startTime: 0, fadeIn: true, category: 'rock' },
    //{ id: 'song48', label: 'A Song for Mama', file: audioUrl('/audio/songs/a-song-for-mama.mp3'), startTime: 60, fadeIn: true, category: 'mothers-day' },
    //{ id: 'song49', label: 'The Best Day', file: audioUrl('/audio/songs/the-best-day.mp3'), startTime: 50, fadeIn: true, category: 'mothers-day' },
    //{ id: 'song50', label: 'Mama', file: audioUrl('/audio/songs/spice-girls-mama.mp3'), startTime: 30, fadeIn: true, category: 'mothers-day' },
    //{ id: 'song51', label: "Mama's Song", file: audioUrl("/audio/songs/Mama_s Song.mp3"), startTime: 60, fadeIn: true, category: 'mothers-day' },
    //{ id: 'song52', label: 'Mama Said', file: audioUrl('/audio/songs/mama-said.mp3'), startTime: 0, fadeIn: false, category: 'mothers-day' },
  ],

  // Selectable background music for pregame intro sequence
  pregameBackgroundOptions: [
    { id: 'song4', label: "Baba O'Riley", file: audioUrl('/audio/songs/baba-o-riley.mp3'), startTime: 30, fadeIn: true },
    { id: 'song15', label: 'Eye of the Tiger', file: audioUrl('/audio/songs/eye-of-the-tiger.mp3'), startTime: 0, fadeIn: true },
    { id: 'song5', label: 'Back In Black', file: audioUrl('/audio/songs/back-in-black.mp3'), startTime: 5, fadeIn: true },
    { id: 'song37', label: 'The Imperial March', file: audioUrl('/audio/songs/the-imperial-march.mp3'), startTime: 0, fadeIn: true },
    { id: 'song44', label: 'Welcome To The Jungle', file: audioUrl('/audio/songs/welcome-to-the-jungle.mp3'), startTime: 0, fadeIn: true },
    { id: 'song39', label: 'Thunderstruck', file: audioUrl('/audio/songs/thunderstruck.mp3'), startTime: 0, fadeIn: true },
    { id: 'song21', label: 'Jump Around', file: audioUrl('/audio/songs/jump-around.mp3'), startTime: 0, fadeIn: true },
    { id: 'song14', label: 'Enter Sandman', file: audioUrl('/audio/songs/enter-sandman.mp3'), startTime: 0, fadeIn: true },
  ],

  // Background loops for pregame announcements (player intros)
  pregame: [
    { id: 'intro-zaro', label: 'Gabriel Zaro Intro', file: audioUrl('/audio/pregame/intro-01-gabriel-zaro.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-ullrich', label: 'Henry Ullrich Intro', file: audioUrl('/audio/pregame/intro-02-henry-ullrich.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-doshi', label: 'Sameer Doshi Intro', file: audioUrl('/audio/pregame/intro-03-sameer-doshi.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-tang', label: 'Oliver Tang Intro', file: audioUrl('/audio/pregame/intro-04-oliver-tang.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-khanshab', label: 'Ilyaas Khanshab Intro', file: audioUrl('/audio/pregame/intro-05-ilyaas-khanshab.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-xia', label: 'Xavier Xia Intro', file: audioUrl('/audio/pregame/intro-06-xavier-xia.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-smith', label: 'Hunter Smith Intro', file: audioUrl('/audio/pregame/intro-07-hunter-smith.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-chew', label: 'Jasper Chew Intro', file: audioUrl('/audio/pregame/intro-08-jasper-chew.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-shin', label: 'Ryan Shin Intro', file: audioUrl('/audio/pregame/intro-09-ryan-shin.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-schmidt', label: 'Stan Schmidt Intro', file: audioUrl('/audio/pregame/intro-10-stan-schmidt.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-bedi', label: 'Devon Bedi Intro', file: audioUrl('/audio/pregame/intro-11-devon-bedi.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-teseo', label: 'Nicholas Teseo Intro', file: audioUrl('/audio/pregame/intro-12-nicholas-teseo.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-oconnor', label: 'Liam OConnor Intro', file: audioUrl('/audio/pregame/intro-13-liam-oconnor.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-end', label: 'Intro End', file: audioUrl('/audio/pregame/intro-end.mp3'), startTime: 0, fadeIn: false },
    { id: 'intro-monsters', label: 'Lake Monsters Intro', file: audioUrl('/audio/pregame/intro-lake-monsters-lineup.mp3'), startTime: 0, fadeIn: false },
    { id: 'national-anthem', label: 'National Anthem', file: audioUrl('/audio/pregame/national-anthem.mp3'), startTime: 0, fadeIn: false },
  ],
};


